package model;
// Generated Nov 3, 2016 6:35:21 PM by Hibernate Tools 4.3.1



/**
 * TblCitas generated by hbm2java
 */
public class TblCitas  implements java.io.Serializable {


     private Integer id;
     private Integer idPaciente;
     private Integer assisted;
     private Integer deleted;
     private Integer idSesion;
     private Integer tipo;

    public TblCitas() {
    }

    public TblCitas(Integer idPaciente, Integer assisted, Integer deleted, Integer idSesion) {
       this.idPaciente = idPaciente;
       this.assisted = assisted;
       this.deleted = deleted;
       this.idSesion = idSesion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Integer getAssisted() {
        return this.assisted;
    }
    
    public void setAssisted(Integer assisted) {
        this.assisted = assisted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
    public Integer getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(Integer idSesion) {
        this.idSesion = idSesion;
    }

    public Integer getTipo() {
        return tipo;
    }

    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }




}


