package model;
// Generated Nov 3, 2016 6:35:21 PM by Hibernate Tools 4.3.1



/**
 * TblPacientes generated by hbm2java
 */
public class TblPacientes  implements java.io.Serializable {


     private Integer id;
     private Integer idUsuario;
     private String nombre;

    public TblPacientes() {
    }

    public TblPacientes(Integer idUsuario, String nombre) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


