package model;
// Generated Nov 3, 2016 6:35:21 PM by Hibernate Tools 4.3.1



/**
 * TblTratamientos generated by hbm2java
 */
public class TblTratamientos  implements java.io.Serializable {


     private Integer id;
     private Integer idPaciente;
     private Integer idUsuario;
     private Integer idCita;
     private Integer deleted;
     private String tratamiento;

    public TblTratamientos() {
    }

    public TblTratamientos(Integer idPaciente, Integer idUsuario, Integer idCita, Integer deleted, String tratamiento) {
       this.idPaciente = idPaciente;
       this.idUsuario = idUsuario;
       this.idCita = idCita;
       this.deleted = deleted;
       this.tratamiento = tratamiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }




}


